export const initialHookahs = [
  {
    _id: '65f01a010000000000000001',
    title: 'The Imperial Obsidian',
    slug: 'the-imperial-obsidian',
    tagline: 'The Ultimate 4-Hose VIP Statement Piece',
    description: 'Forged from matte-black aerospace aluminum and mouth-blown Bohemian crystal glass. Features four synchronized magnetic valves for effortless multi-user draw without pressure loss. Includes integrated remote-controlled LED base lighting.',
    hourlyRate: 85,
    minimumHours: 2,
    images: [
      '/images/imperial_obsidian.jpg',
      'https://images.unsplash.com/photo-1542332213-9b5a5a3fad35?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-party-lights-in-a-nightclub-43305-large.mp4',
    hosesCount: 4,
    heightCm: 80,
    material: 'Matte Black Anodized Aluminum & Bohemian Crystal',
    flavorOptions: ['Double Apple Reserve', 'Mint Breeze', 'Blueberry Ice', 'Peach Mango Smoothie', 'Love 66'],
    eventSuitability: ['Weddings', 'Corporate events', 'Private events', 'Birthdays'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    _id: '65f01a010000000000000002',
    title: 'The Sovereign Gold Edition',
    slug: 'the-sovereign-gold-edition',
    tagline: '24K Electroplated Luxury Centerpiece',
    description: 'Pure opulence designed for high-end celebrations. Adorned with 24K gold electroplated filigree stem, heavy brass tray, and custom dual velvet-touch silicone hoses with golden metal tips.',
    hourlyRate: 95,
    minimumHours: 2,
    images: [
      '/images/sovereign_gold.jpg',
      'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-close-up-of-champagne-glasses-at-a-party-43285-large.mp4',
    hosesCount: 2,
    heightCm: 75,
    material: '24K Gold Electroplated Brass & Heavy Crystal Vase',
    flavorOptions: ['White Gummy Bear', 'Citrus Mint', 'Grape Mint', 'Watermelon Freeze'],
    eventSuitability: ['Weddings', 'Private events', 'Birthdays', 'Corporate events'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    _id: '65f01a010000000000000003',
    title: 'The Midnight Velvet',
    slug: 'the-midnight-velvet',
    tagline: 'Sleek Dark Elegance for Modern Nights',
    description: 'Designed for intimate luxury gatherings and lounge setups. Deep charcoal smoked glass bowl paired with soft-touch velvet hoses and dual heat-management fruit head attachment.',
    hourlyRate: 65,
    minimumHours: 2,
    images: [
      '/images/midnight_velvet.jpg',
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-lights-in-a-disco-nightclub-43306-large.mp4',
    hosesCount: 2,
    heightCm: 70,
    material: 'Charcoal Smoked Glass & Brushed Stainless Steel',
    flavorOptions: ['Lemon Mint', 'Blueberry Mint', 'Spiced Chai', 'Passion Fruit'],
    eventSuitability: ['House parties', 'Birthdays', 'Private events', 'College events'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    _id: '65f01a010000000000000004',
    title: 'The Neon Royale Cube',
    slug: 'the-neon-royale-cube',
    tagline: 'RGB Illumination High-Energy Party Setup',
    description: 'Ultra-durable acrylic cube design engineered to withstand active party environments without tipping. Equipped with dynamic RGB strobe & ambient glow remote lighting modes.',
    hourlyRate: 55,
    minimumHours: 2,
    images: [
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-people-dancing-at-a-party-43304-large.mp4',
    hosesCount: 4,
    heightCm: 45,
    material: 'Shatterproof Acrylic Cube & Anodized Aluminum',
    flavorOptions: ['Mango Ice', 'Pina Colada', 'Watermelon Chill', 'Gum Mint'],
    eventSuitability: ['House parties', 'College events', 'Birthdays'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    _id: '65f01a010000000000000005',
    title: 'The Artisan Brass Mirage',
    slug: 'the-artisan-brass-mirage',
    tagline: 'Hand-Engraved Authentic Heritage Hookah',
    description: 'Traditional craftsmanship meets modern airflow engineering. Solid brass stem hand-carved by master artisans, topped with an authentic clay Phunnel bowl for maximum flavor output.',
    hourlyRate: 75,
    minimumHours: 2,
    images: [
      'https://images.unsplash.com/photo-1578474846511-04ba529f0b88?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-close-up-of-champagne-glasses-at-a-party-43285-large.mp4',
    hosesCount: 1,
    heightCm: 85,
    material: 'Solid Hand-Engraved Egyptian Brass & Clay Phunnel Bowl',
    flavorOptions: ['Double Apple Heritage', 'Grape Mint', 'Sweet Melon', 'Mint Extra Cold'],
    eventSuitability: ['Weddings', 'Private events', 'Corporate events'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    _id: '65f01a010000000000000006',
    title: 'The Phantom Carbon',
    slug: 'the-phantom-carbon',
    tagline: 'High-Tech Carbon Fiber & Magnetic Purge',
    description: 'Featherlight genuine 3K carbon fiber shaft with ultra-fast vertical purge system. Unmatched airflow mechanics designed for serious shisha aficionados.',
    hourlyRate: 50,
    minimumHours: 2,
    images: [
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-party-lights-in-a-nightclub-43305-large.mp4',
    hosesCount: 2,
    heightCm: 65,
    material: '3K Real Carbon Fiber & Surgical Stainless Steel',
    flavorOptions: ['Blueberry Mint', 'Gum Cinnamon', 'Lemon Blast', 'Peach Chill'],
    eventSuitability: ['House parties', 'Birthdays', 'Private events'],
    isFeatured: false,
    isAvailable: true,
  },
];

export const initialBookings = [
  {
    _id: '65f02b010000000000000001',
    bookingReference: 'HKH-2026-8942',
    customer: {
      fullName: 'Alexander Wright',
      email: 'alex.wright@example.com',
      phone: '+1 (555) 234-5678',
    },
    eventDetails: {
      eventType: 'Private event',
      eventDate: new Date(Date.now() + 86400000 * 3),
      startTime: '20:00',
      durationHours: 4,
      venueAddress: '742 Evergreen Terrace, Penthouse Suite, Downtown',
      guestCount: 25,
      specialNotes: 'Please include extra coconut coals and LED base set to gold pulse.',
    },
    items: [
      {
        hookahId: '65f01a010000000000000001',
        title: 'The Imperial Obsidian',
        hourlyRate: 85,
        quantity: 2,
      },
    ],
    pricing: {
      hourlySubtotal: 170,
      estimatedTotal: 680,
    },
    status: 'Pending',
    adminNotes: 'Awaiting venue security clearance before confirming.',
    createdAt: new Date(Date.now() - 3600000 * 5),
  },
];
